TeamBasedInquiryLearning/linear-algebra

tex/modules/4-A/activities.tex
Typos in this slide need to be fixed. I did not build the slides because `make` seems to be currently broken on my machine (perhaps related to the sectioning work @siwelwerd did?). Requesting @siwelwerd to review this fix, build the slides to this branch and update the PR, then approve & merge the PR into master.
=> question should be about RREF A

exercises/mastr/V04.sage, exercises/mastr/V04.xml.erb
Produces exercises like
Would close #118
=> limit V04 exercises to R3

ptx/source/02-V/01.ptx, ptx/source/02-V/02.ptx, ptx/source/02-V/03.ptx, ptx/source/02-V/05.ptx, ptx/source/02-V/07.ptx, ptx/source/02-V/08.ptx, ptx/source/03-A/01.ptx
=> Change P^n to P_n, addresses #129

ptx/source/01-E/01.ptx, ptx/source/01-E/02.ptx, ptx/source/01-E/03.ptx, ptx/source/02-V/01.ptx, ptx/source/02-V/02.ptx, ptx/source/02-V/03.ptx, ptx/source/02-V/04.ptx, ptx/source/02-V/05.ptx, ptx/source/02-V/06.ptx, ptx/source/02-V/07.ptx, ptx/source/02-V/08.ptx, ptx/source/02-V/09.ptx, ptx/source/03-A/01.ptx, ptx/source/03-A/02.ptx, ptx/source/03-A/03.ptx, ptx/source/03-A/04.ptx, ptx/source/04-M/01.ptx, ptx/source/04-M/02.ptx, ptx/source/04-M/03.ptx, ptx/source/04-M/04.ptx, ptx/source/05-G/01.ptx, ptx/source/05-G/02.ptx, ptx/source/05-G/03.ptx, ptx/source/05-G/04.ptx
=> Add videos, addresses #143

ptx/source/01-E/02.ptx, ptx/source/01-E/03.ptx, ptx/source/02-V/02.ptx, ptx/source/02-V/03.ptx, ptx/source/02-V/05.ptx, ptx/source/02-V/06.ptx, ptx/source/02-V/07.ptx, ptx/source/02-V/09.ptx, ptx/source/03-A/03.ptx, ptx/source/03-A/04.ptx, ptx/source/04-M/01.ptx, ptx/source/04-M/02.ptx, ptx/source/04-M/03.ptx, ptx/source/04-M/04.ptx, ptx/source/05-G/01.ptx, ptx/source/05-G/02.ptx, ptx/source/05-G/04.ptx
Sage cells are implemented now, closing #151
=> Proofreading edits

source/01-LE/02.ptx
=> Simple typo correction

source/02-VS/06.ptx
I think after accepting this, it will be necessary to run `pretext deploy` (I am not sure how `pretext deploy` plays with branches)
=> Redo VS6 activities to address #208

exercises/outcomes/AT/AT5/generator.sage
Closes #218 by reducing the exponents.  Students should have to (at worst) expand (c+d)^3
=> Reduce exponents

project.ptx
One line change in project.ptx so that one can generate the tex file
=> Added option for generating tex via print-latex

LICENSE.md, license.txt, source/meta/copyright.ptx
I think this addresses our email discussion @siwelwerd, thoughts?
=> stab at revamped licensing

source/02-EV/05.ptx
=> clarity in activity 2.5.8

source/02-EV/05.ptx
See discussion in #257; this PR reflects the will of the people as determined by very scientific polling efforts.
=> Homogenize formatting of i hat, j hat, k hat

source/02-EV/07.ptx
=> convert video game to computer animation reference

source/02-EV/03.ptx, source/02-EV/samples/03.ptx, source/03-AT/01.ptx
=> clean up and align EV3 and AT1 remarks

source/02-EV/05.ptx
=> Clarify definition 2.5.3

exercises/outcomes/Extra/Extra1Midterm/template.xml
For convenience, this adds a concise answer key for the checkit MCQ midterm.
=> add mcq answer key to end of midterm

exercises/outcomes/AT/AT5/generator.sage
=> add assertions to track down error

exercises/outcomes/AT/AT1/template.xml
Rejiggering the generated "final answer" here to better suggest to students that both sides of the addition/multiplication requirements should be found to equal the given expression (rather than just assuming they will both work out).
=> Provide more scaffolding for generated AT1 solution

source/01-LE/01.ptx, source/02-EV/01.ptx
=> define Euclidean vectors and notation upfront

exercises/outcomes/EV/EV3/generator.sage, exercises/outcomes/EV/EV3/template.xml
Currently we don't give much direction in our brief answer in EV3 task 3:
This provides a bit more detail on what's expected:
=> expand answer to EV3 task 3

source/03-AT/05.ptx
=> Remove "non-Euclidean"

source/04-MX/03.ptx, source/04-MX/04.ptx
=> Remove deprecated label attribute

source/03-AT/06.ptx
=> Add dimension scaffolding to AT6

source/02-EV/01.ptx, source/02-EV/02.ptx, source/02-EV/03.ptx, source/02-EV/05.ptx, source/02-EV/06.ptx, source/03-AT/06.ptx
=> Add asides about use of term "vector space"

exercises/outcomes/MX/MX4/generator.sage, exercises/outcomes/MX/MX4/template.xml
=> use all three operation types in MX4

source/03-AT/03.ptx
Clean PR implementing just @jkostiuk's proposed changes to AT3 from #315 .  Closes #295
=> Add scaffolding, closes #295

exercises/outcomes/AT/AT5/generator.sage
=> AT5 refactor

xsl/slides.xsl
=> Include notes in slides

source/03-AT/03.ptx
=> remove redundant activity in at3

source/02-EV/03.ptx, source/02-EV/07.ptx
=> changing definition of subspace, introducing new activities

source/01-LE/02.ptx
=> Ensure only single row op

site/index.html
=> Add slides link to landing page

source/01-LE/01.ptx, source/01-LE/02.ptx, source/01-LE/03.ptx, source/01-LE/04.ptx, source/02-EV/01.ptx, source/02-EV/02.ptx, source/02-EV/03.ptx, source/02-EV/04.ptx, source/02-EV/05.ptx, source/02-EV/06.ptx, source/02-EV/07.ptx, source/03-AT/01.ptx, source/03-AT/02.ptx, source/03-AT/03.ptx, source/03-AT/04.ptx, source/03-AT/05.ptx, source/03-AT/06.ptx, source/04-MX/01.ptx, source/04-MX/02.ptx, source/04-MX/03.ptx, source/04-MX/04.ptx, source/05-GT/01.ptx, source/05-GT/02.ptx, source/05-GT/03.ptx, source/05-GT/04.ptx
=> Fix 2024 edition links

source/02-EV/02.ptx
=> Typo fix, closes #352

source/03-AT/02.ptx
=> Typo fix, closes #361

exercises/outcomes/MX/MX4/generator.sage
=> Fix index error in MX4 Checkit

source/02-EV/01.ptx
Today @jkostiuk and I set up this proof of concept that he wanted to do on a fork of the book, but I thought it might be a nice contribution to the book itself. Jordan can correct me but here's the gist:
The "Warm Up" serves as a mini readiness assurance activity that's not necessary for the scaffolding of the section, but could still help reinforce prior knowledge going into a section. Each instructor can decide how to use it for their class.
The "Cool Down" provides students some next steps to help them prepare for the next section.
What are your thoughts @siwelwerd?
=> Add warmup/cooldown to EV1

source/05-GT/samples/01.ptx
=> Fix notation of row operations in G1 sample problem

source/02-EV/02.ptx
Here is my suggestion for warmup and cooldown for EV2, addressing #370 . Let me know what you guys think. 
For the warmup, I wanted them to think in terms of analogies to build some language fluency. The activities in EV2 do a good job of having students get into the computations quickly so didn't feel it was needed in the warmup. 
For the cooldowns generally, I want to avoid them doing straight practice--the CheckIt problems already do that. I'd like them to instead flex some adjacent muscles we don't workout in the activities. For this one, I thought proving the fact that we need at least n vectors to span R^n would be a good way to both reinforce the concept, and has the added benefit of making it clear that (a) we don't prove the fact and that (b) they are capable of proving the fact. …
=> Warmup and cooldown for EV2

source/02-EV/04.ptx
Here's my draft of a warmup/cooldown for EV4, continuing to address #370. 
My idea for the warmup was to have student gently prodded into activity that follows, having them consider a non-homogenous equation and then the corresponding homogenous equation obtained by moving the LHS vector to the RHS. 
The cooldown is designed to further build visual/geometric and verbal fluency through analogy.
Also squashed a typo.
=> EV4WarmupCooldownDraft

source/02-EV/02.ptx, source/02-EV/03.ptx
Addresses #370
Here's a draft of a warmup/cooldown for EV3. The Warmup is pretty basic, but my hope is that helps students wake up with a concrete example so the following activities feel a little more "oh, we just did a specific example and are generalizing". 
The Cooldown here actually has two parts, largely because I felt there were two key things I wanted students to practice. First, they learned a new important word and I want to continue the analogy game. Second, I want them to see common mistakes and reflect on why they are mistakes.
=> Draft EV3 WarmupCooldown

source/02-EV/06.ptx
=> DraftWarmupCooldown for EV6

source/02-EV/05.ptx
Here's a draft of warmup/cooldown for EV5, addressing #370 
Largely focussed on definitions and analogy.
=> EV5WarmupCooldowndraft

source/02-EV/04.ptx
addresses feedback from #375
As I was writing, I realized that what I *most* wanted my students to think about in this warmup was the relationship between a non-homogenous vector equation and the homogenized equation obtained by moving the RHS over to the LHS and introducing a variable. The fact that the zero vector is a "free" solution to this equation appears readily in the class activities as is and so I don't think this new warmup is missing anything by not addressing it.
=> edits to EV4 warmup

source/02-EV/07.ptx
Further addresses #370
Since homogenous equations were introduced in EV3, it felt natural to me to just use the existing first two activities as the warmup. This means that running this lesson wouldn't really be any different than last term, but I like that the warmup further sets the expectation that we are expecting our students to be able to recall this information. 
For the cooldown, this is more of a language thing that serves as somewhat of a cooldown for the whole EV module.
=> suggestion for a warmup and cooldown for EV7

source/01-LE/04.ptx
Further addresses #370
Warmup here is simple recall of LE3. 
the cooldown, like the cooldown I wrote for EV is focussed around imprecise/incorrect use of terminology and/or revealing common mistakes.
=> LE4 warm up and cooldown

source/01-LE/01.ptx, source/01-LE/03.ptx
Further address #370
The warmup here is focussed on recalling the definition of RREF and setting the expectation that students are indeed studying it to recall. 
The cooldown is mostly about having students tie up a loose end. 
I added cross-references as needed for flow.
=> LE3 warmup and cooldown

source/03-AT/01.ptx, source/03-AT/02.ptx, source/03-AT/03.ptx, source/03-AT/04.ptx, source/03-AT/05.ptx, source/03-AT/06.ptx
Here are my suggestions for warmup and cooldowns for AT, further addressing #370. 
Each separate commit is a different section; please let me know if this workflow is okay, if there are modifications you'd like me to make.
=> AT-warmups

source/01-LE/01.ptx
Further address #370
Here is my suggestion for a warmup and cooldown for LE1. The warmup is basically just addressing the geometry in the RAP; the cooldown has them think a little more critically about the notational construct of augmented matrix. 
I also took the opportunity while I was in LE1 to splice in a definition of coefficient matrix to Definition 1.1.16--let me know what you think.
=> LE1CoolDownWarmup+DefnEdit

source/04-MX/01.ptx, source/04-MX/02.ptx, source/04-MX/03.ptx, source/04-MX/04.ptx
further addressing #370, this PR has warm up and cooldowns for section MX
=> MX-WarmUps

source/05-GT/01.ptx, source/05-GT/02.ptx, source/05-GT/03.ptx, source/05-GT/04.ptx
Warmups and Cooldowns for GT, further addressing #370. 
Meta note: I'm still open to suggestions for a different name other than cooldown. 
Let me know when/were I should be contributing some text to explain to instructors what these things are.
=> GT-Warmup-Cooldown

source/01-LE/01.ptx, source/01-LE/03.ptx, source/02-EV/01.ptx, source/02-EV/02.ptx, source/03-AT/02.ptx
=> Define a matrix
